[workspace]
authors = ["assadiab <assa.diabira@etu.u-paris.fr>"]
channels = ["conda-forge"]
name = "Projet_kaggle"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
kaggle = ">=1.7.4.5,<2"
pydicom = ">=3.0.1,<4"
pandas = ">=2.3.3,<3"
pytest = ">=8.4.2,<9"
