[workspace]
authors = ["assadiab <assa.diabira@etu.u-paris.fr>"]
channels = ["conda-forge"]
name = "Projet_kaggle"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
kaggle = ">=1.7.4.5,<2"
pydicom = ">=3.0.1,<4"
pandas = ">=2.3.3,<3"
pytest = ">=8.4.2,<9"
pytorch = ">=2.8.0,<3"
opencv = ">=4.12.0,<5"
simpleitk = ">=2.5.2,<3"
pip = ">=25.2,<26"
matplotlib = ">=3.10.7,<4"
seaborn = ">=0.13.2,<0.14"
imageio = ">=2.37.0,<3"
